import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from '@/store/StoreProvider';
import Navbar from '@/components/Navbar/Navbar';
import ThemeProvider, { ThemeContext } from '@/contexts/ThemeContext';
import ClientThemeWrapper from '@/contexts/ClientThemeWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Baumel Márton Portfolio Site',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <html lang='en'>
                <body className={inter.className}>
                    <ThemeProvider>
                        <ClientThemeWrapper>
                            <Navbar />
                            <div>{children}</div>
                        </ClientThemeWrapper>
                    </ThemeProvider>
                </body>
            </html>
        </StoreProvider>
    );
}
